from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('my_shops/',views.my_shops,name='my_shops'),
    path('my_shops2/',views.my_shops2,name='my_shops2'),
    path('my_shops3/',views.my_shops3,name='my_shops3'),
    path('shop_detail/<int:good_id>',views.shop_detail,name='shop_detail'),
    path('login/',views.Login.as_view(),name='login'),
    path('face_login/',views.FaceLogin.as_view(),name='face_login'),
    path('register/',views.Register.as_view(),name='register'),
    path('face_register/',views.Faceregister.as_view(),name='face_register'),
    path('is_face/',views.IsFace.as_view(),name="isface"),
    path('is_face1/',views.IsFace.as_view(),name="isface1"),
    path('exit/',views.exit_login,name="exit"),
    path('weding_detail/',views.weding_detail,name='weding_detail'),
    path('skip_page/<int:everypage>', views.skip_page, name='skip_page'),
    path('skip_good/<keyword>/<int:everypage>',views.skip_goods,name="skip_goods"),
    path('fill_form/',views.fill_form,name='fill_form'),
    path('weding_detail/2/',views.weding_detail_page2,name='weding_detail_page2'),
    path('weding_detail/3/',views.weding_detail_page3,name='weding_detail_page3'),
    path('weding_detail/4/',views.weding_detail_page4,name='weding_detail_page4'),
    path('weding_detail/5/',views.weding_detail_page5,name='weding_detail_page5'),
    path('weding_detail/6/',views.weding_detail_page6,name='weding_detail_page6'),
    path('weding_detail/7/',views.weding_detail_page7,name='weding_detail_page7'),
    path('weding_detail/8/',views.weding_detail_page8,name='weding_detail_page8'),
    path('weding_detail/9/',views.weding_detail_page9,name='weding_detail_page9'),
    path('insert_good/<int:shop_id>',views.insert_good,name='insert_good'),
    path('clear/',views.clear,name='clear'),
    path('delete_one/<int:one_id>/',views.delete_one,name='delete_one'),
    path('reduce/<int:p_id>/',views.reduce,name='reduce'),
    path('puls/<int:p_id>/',views.puls,name='puls'),
    path('info_id/',views.info_id,name='info_id'),
    path('insert_good/<res>',views.insert_order,name="insert_order"),
    path('orders/',views.ordering,name="orders"),
    path('order_form/',views.order_from,name="order_form"),
    path('order_form1/',views.order_from1,name="order_form1"),
    path('delete_order/<int:d_id>',views.delete_order,name='delete_order')
]