# Generated by Django 2.0 on 2019-05-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllDiamonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=255)),
                ('good_price', models.IntegerField()),
                ('sell_number', models.IntegerField()),
                ('comment_number', models.IntegerField()),
                ('belong_name', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('good_size', models.CharField(max_length=255)),
                ('main_diamond', models.CharField(blank=True, max_length=255, null=True)),
                ('assitant_diamond', models.CharField(blank=True, max_length=255, null=True)),
                ('send_date', models.CharField(blank=True, max_length=255, null=True)),
                ('good_exists', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_img', models.TextField(blank=True, null=True)),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('good_img', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_diamonds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllDiamondUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamond_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'all_diamond_urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
