# Generated by Django 2.0 on 2019-05-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alldiamonds',
            options={},
        ),
        migrations.AlterModelOptions(
            name='alldiamondurls',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
