# Generated by Django 2.0 on 2019-05-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20190521_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alldiamonds',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='alldiamondurls',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
