# Generated by Django 2.0 on 2019-05-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20190521_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alldiamonds',
            options={},
        ),
        migrations.AlterModelOptions(
            name='alldiamondurls',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
