# Generated by Django 2.0 on 2019-05-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20190521_1955'),
    ]

    operations = [
    ]
