# Generated by Django 2.0 on 2019-05-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20190521_1959'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alldiamonds',
            table=None,
        ),
        migrations.AlterModelTable(
            name='alldiamondurls',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
