# Generated by Django 2.0 on 2019-05-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20190521_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alldiamonds',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
