# Generated by Django 2.0 on 2019-05-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20190521_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alldiamondurls',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='alldiamonds',
            table='all_diamonds',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
