# Generated by Django 2.0 on 2019-05-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_auto_20190521_2005'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alldiamonds',
            table='alldiamonds',
        ),
        migrations.AlterModelTable(
            name='alldiamondurls',
            table='all_diamond_urls',
        ),
    ]
