# Generated by Django 2.0 on 2019-05-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_auto_20190524_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForms',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(max_length=255)),
                ('sender_address', models.CharField(max_length=255)),
                ('sender_post', models.CharField(max_length=255)),
                ('sender_postcode', models.CharField(max_length=255)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_phone', models.CharField(max_length=255)),
                ('receiver_address', models.CharField(max_length=255)),
                ('receiver_postcode', models.CharField(max_length=255)),
                ('shop_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'order_forms',
                'managed': False,
            },
        ),
    ]
